---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangyouzhan.
--- DateTime: 2019-02-20 21:30
---

--print "enter your expression:"
--
--local l = io.read()
--local func = assert(loadstring("return " .. l))
--print("the value of your expression is " .. func())


print(loadlib())




--local i = 0
--f = loadstring("i = i + 1")
--print(f())
--g = function () i = i + 1 end
--print(g())



--f = loadstring("i = i + 1")
--i = 0
--f(); print(i)
--f(); print(i)

--f  = loadstring("local a = 10; return a + 20")
--print(f())
--print(loadstring("i i"))




--a = {"one", "two", "three"}
--for i, v in ipairs(a) do
--    print(i, v)
--end




--function allwords()
--    local line = io.read()
--    local pos = 1
--    return function()
--        while line do
--            local s, e = string.find(line, "%w+", pos)
--            if s then
--                pos = e + 1
--                return string.sub(line, s, e)
--            else
--                line = io.read()
--                pos = 1
--            end
--        end
--        return nil
--    end
--end
--
--for word in allwords() do
--    print(word)
--end






--function list_iter(t)
--    local i = 0
--    local n = table.
--    return function()
--        i = i + 1
--        if i <= n then
--            return t[i]
--        end
--    end
--end
--
--
--
--t = {10, 20, 30}
--iter = list_iter(t)
--while true do
--    local element = iter()
--    if element == nil then break end
--    print(element)
--end
--Lib = {
--    foo = function(x, y) return x + y end,
--    goo = function(x, y) return x - y end
--}



--Lib = {}
--
--Lib.foo = function(x, y) return x + y end
--Lib.goo = function(x, y) return x - y end
--print(Lib)



--function newCounter()
--    local i = 0
--    return function()
--        i = i + 1
--        return i
--    end
--end
--
--c1 = newCounter()
--print(c1())
--print(c1())



