---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangyouzhan.
--- DateTime: 2019-02-21 22:33
---



--for n in pairs(_G) do print(n) end

--a = {}
--for line in io.lines() do
--    table.insert(a, line)
--    if line == 1 then
--        break
--    end
--
--end
--
--print(table.unpack(a))

lines = {
    luaH_set = 10,
    luaH_get = 24,
    luaH_present = 48
}

a = {}
for n in pairs(lines) do table.insert(a,n) end
table.sort(a)
for i, n in ipairs(a) do print(n) end
