---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by cape.
--- DateTime: 2019/2/19 12:45
---

--print(type("What is my type"))
--t = 10
--
--print(type(5.8 * t))
--print(type(true))
--print(type(print))
--print(type(nil))
--print(type(type(ABC)))

local n = 5
function myfunction()
    n = n / nil
end


if pcall(myfunction) then
    print("sucess")
else
    print("Failure")
end





