---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by cape.
--- DateTime: 2018/6/19 14:51
---

print("asdfasdf")

local function fact(n)
    if n == 0 then
        return 1
    else
        return n * fact(n -1)
    end
end

print("enter a number:")
local a = io.read("*n")
print(fact(a))



