
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by cape.
--- DateTime: 2019/2/20 19:21
---


local _, x = string.find(s,p)








--local printResult = ""
--function print(...)
--    for i, v in ipairs(arg) do
--        printResult = printResult .. tostring(v) .. "\t"
--    end
--    printResult = printResult .. "\n"
--end

--print(12, 2, 34)

