---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by cape.
--- DateTime: 2019/2/20 18:57
---

f = string.find
a = {"hello11", "11"}
print(f(unpack(a)))


function unpack(t, i)
    i = i or 1
    if t[i] then
        return t[i], unpack(t, i + 1)
    end
end


function maximu(a)
    local mi = 1  -- maximu index
    local m = a[mi]   -- maximu value
    for i, val in ipairs(a) do
        if val > m then
            mi = i
            m = val
        end
    end
    return m, mi
end

--print(maximu({8, 10, 23, 12, 5}))
function foo0() end

function foo1() return 'a' end
function foo2() return "a", 'b' end

--x, y = foo2()
--print(x, y)
--x, y = nil, nil
--x = foo2()
--print(x, y)
--x, y = nil,nil
--x, y , z = 10, foo2()
--print(x, y , z)
--a = {foo0()}
--print(a)
--a = {foo1(),4}
--print(a)

--function foo(i)
--    if i == 0 then return foo0()
--    elseif i == 1 then foo1()
--    elseif i == 2 then foo2()
--    end
--end
--
--
--print((foo2()))
--print(foo(1))




